concert/config/routes.rb
Rails.application.routes.draw do
  resources :events 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

concert/app/models/event.rb
class Event < ApplicationRecord
end

concert/app/controllers/events_controller.rb
class EventsController < ApplicationController
	def index
		@my_event = Event.all
		render 'index'
	end 
	def show
		@my_event = Event.find(params[:id])
		render 'show'
	end 
	def new
		@my_event = Event.new
		render 'new'
	end 
	def create 
		@my_event = Event.new(
			:artist => params[:event][:artist],
			:venue => params[:event][:venue],
			:city => params[:event][:city],
			:date => params[:event][:date],
			:price => params[:event][:price],
			:description => params[:event][:description])
		@my_event.save
		redirect_to events_path(@my_event)
	end 
end

concert/app/controllers/resource_controller.rb
class ResourceController < ApplicationController
	def index
		@resources = Resource.all
		render 'index'
	end  
end

concert/app/helpers/events_helper.rb
module EventsHelper
end

concert/app/helpers/resource_helper.rb
module ResourceHelper
end

concert/app/views/events/index.html.erb
<div class="main">

	<h2> Home  </h2>

	<h3> All Concerts </h3>
		<ul>
			<% @my_event.each do |event| %>
				<li>
					<%= event.artist %>
					<% if event.description.present? %>
					-<%= link_to "See Details", "/events/#{event.id}"%>
					<%end%>
				</li>
				<%end%>
		</ul>

	<br>
	<br>

	<h3> Concerts Happening Today: </h3>
	<ul>
		<% @my_event.each do |event| %>
			
			<% if event.date == Date.today %>
				<%= event.artist %>
				-<%= link_to "See Details", "/events/#{event.id}"%>
			<%end%>
			
		<%end%>
	</ul>
	<br>
	<br>
		 <h4><%= link_to "Add a concert", new_event_path%></h4>



<div class ="bar">
	<h3>Events later this month:</h3>
 	<select>
		<% @my_event.each do |event| %>
			<% if  Date.today <= event.date && event.date < Date.today.end_of_month %>
				  <option>
				  <%= event.artist %>				
				  </option>
				<%end%>
		<%end%>
	 </select>


 </div>





</div>

concert/app/views/events/new.html.erb
<h3>Add Concerts Here! </h3>

<br> 
<br>
<%= form_for @my_event do |f| %>
	<%=f.label :artist %>
	<%=f.text_field :artist %>
<br>
<br>
	<%=f.label :venue %>
	<%=f.text_field :venue %>
<br>
<br>
	<%=f.label :city %>
	<%=f.text_field :city %>
<br>
<br>
	<%=f.label :date %>
	<%=f.date_field :date %>
<br>
<br>
	<%=f.label :price %>
	<%=f.text_field :price %>
<br>
<br>
	<%=f.label :description %>
	<%=f. text_area :description %>

	<%= f.button %>

<br>
<br>

<%= link_to "Home", events_path %>
<%end %>

concert/app/views/events/show.html.erb
<div class="concert">

<h3> Concert Details </h3>
Artist: <%= @my_event.artist %> 
<br>
Venue: <%= @my_event.venue %> 
<br>
City: <%= @my_event.city %>
<br> 
Date: <%= @my_event.date %> 
<br>
Ticket price:$<%= @my_event.price %>
<br> 
Event Description:<%= @my_event.description %> 
</div>